apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-config
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |-
{{ .Values.cmExtraConfig.applicationProperties | indent 4 }}


