apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-config
  namespace: {{ .Release.Namespace }}
data:
  application.properties: |-
{{ index .Values.cmExtraConfig "application.properties" | indent 4 }}



