apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-parameters.fullname" . }}
  labels:
    {{- include "backend-parameters.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "backend-parameters.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "backend-parameters.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend-parameters.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: BACKEND_PROFILES_ACTIVE
              value: dev
            - name: ENV_VAR1
              valueFrom:
                configMapKeyRef:
                  name: cm-extra-config
                  key: ENV_VAR1
            - name: ENV_VAR4
              valueFrom:
                secretKeyRef:
                  name: secret-extra-config
                  key: ENV_VAR4
          envFrom:
            - configMapRef:
                name: cm-extra-env
            - secretRef:
                name: secret-extra-env
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: secret-config-volume
              mountPath: /secret-config
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: cm-extra-config
            items:
              - key: application.properties
                path: application.properties
            defaultMode: 420
        - name: secret-config-volume
          secret:
            secretName: secret-extra-config
            items:
              - key: application.secret.properties
                path: application.secret.properties
            defaultMode: 420

