apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  application.secret.properties: |-
{{ .Values.secretExtraConfig.applicationSecretProperties | indent 4 }}



