apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- with .Values.secretExtraEnv }}
  {{ toYaml . | indent 2 }}
  {{- end }}

