apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
  namespace: ff1519a6
type: Opaque
stringData:
  application.secret.properties: |
    secret.key1=secret-value-1
    secret.key2=secret-value-2
