apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
type: Opaque
stringData:
  ENV_VAR4: {{ .Values.secretExtraConfig.ENV_VAR4 | quote }}
  application.secret.properties: |-
{{ .Values.application.secret.properties.from.secret | indent 4 }}



